version: "3"

services:
  backend:
    #build: "./backend"
    image: inqueryio/backend:latest
    platform: linux/amd64
    # Un-comment if using Apple silicon
    #platform: linux/arm64
    container_name: backend
    stop_signal: SIGTERM
    stop_grace_period: 30s
    restart: on-failure
    ports:
      - "3003:3003"
    networks:
      - inquery
    volumes:
      - inquery:/tmp/badger
    environment:
      - DISK_DB_ENCRYPTION_KEY=${DISK_DB_ENCRYPTION_KEY}
      - DISK_DB_LOCATION=/tmp/badger
      - HTTP_API_SERVER_PORT=3003
      - HTTP_API_SERVER_CORS_ALLOW_ORIGINS=${HTTP_API_SERVER_CORS_ALLOW_ORIGINS}
      - HTTP_API_SERVER_AUTH_TOKEN=${HTTP_API_SERVER_AUTH_TOKEN}
  frontend:
    #build: "./frontend"
    image: inqueryio/frontend:latest
    platform: linux/amd64
    # Un-comment if using Apple silicon
    #platform: linux/arm64
    container_name: frontend
    command:
      - /bin/sh
      - -c
      - |
        ./env.sh
        echo "docker"
        NODE_ENV=development runtime-env-cra 
        nginx -g "daemon off;"
    ports:
      - "3000:80"
    networks:
      - inquery
    volumes:
      - ${PWD}/frontend.env:/usr/share/nginx/html/.env
      - ${PWD}/env.sh:/usr/share/nginx/html/env.sh
volumes:
  inquery:
networks:
  inquery:
